/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import domain.Marca;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author csala
 */

public class AltaVehiculo extends javax.swing.JFrame {
    
    /**
     * Creates new form AltaVehiculo
     */
    private Controlador controlador;
    private ListarVehiculosView padre;
    
    public AltaVehiculo() {
        controlador = new Controlador();
        
        initComponents();
        
        this.marcaText.setText("");
        this.paisText.setText("");
        this.patenteText.setText("");
        this.modeloText.setText("");
        this.anioText.setText("0");
        this.cargaText.setText("0");
        this.kmLitroText.setText("0");
        this.litrosExtraText.setText("0");
    }
    
    public AltaVehiculo(ListarVehiculosView padre) {
        initComponents();
        
        controlador = new Controlador();
        this.padre = padre;
        
        this.marcaText.setText("");
        this.paisText.setText("");
        this.patenteText.setText("");
        this.modeloText.setText("");
        this.anioText.setText("0");
        this.cargaText.setText("0");
        this.kmLitroText.setText("0");
        this.litrosExtraText.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        marcaText = new javax.swing.JTextField();
        paisText = new javax.swing.JTextField();
        patenteText = new javax.swing.JTextField();
        modeloText = new javax.swing.JTextField();
        AnioText = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        anioText = new javax.swing.JTextField();
        cargaText = new javax.swing.JTextField();
        kmLitroText = new javax.swing.JTextField();
        litrosExtraText = new javax.swing.JTextField();
        agregarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca:");

        jLabel2.setText("Pais:");

        jLabel3.setText("Patente:");

        jLabel4.setText("Modelo:");

        marcaText.setText("jTextField1");

        paisText.setText("jTextField2");

        patenteText.setText("jTextField3");

        modeloText.setText("jTextField4");

        AnioText.setText("Año:");

        jLabel6.setText("Carga:");

        jLabel8.setText("Km por litro:");

        jLabel7.setText("Litros Extra:");

        anioText.setText("jTextField5");
        anioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioTextKeyTyped(evt);
            }
        });

        cargaText.setText("jTextField6");
        cargaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cargaTextKeyTyped(evt);
            }
        });

        kmLitroText.setText("jTextField7");
        kmLitroText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kmLitroTextKeyTyped(evt);
            }
        });

        litrosExtraText.setText("jTextField8");
        litrosExtraText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                litrosExtraTextKeyTyped(evt);
            }
        });

        agregarButton.setText("Agregar Vehiculo");
        agregarButton.addActionListener(this::agregarButtonActionPerformed);

        salirButton.setText("Salir");
        salirButton.addActionListener(this::salirButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(modeloText))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patenteText, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(paisText)
                            .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(agregarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnioText)
                                .addGap(46, 46, 46)
                                .addComponent(anioText, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(cargaText)))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kmLitroText)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(litrosExtraText)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(marcaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnioText)
                            .addComponent(anioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(paisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(cargaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(patenteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(kmLitroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(modeloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(litrosExtraText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirButton)
                    .addComponent(agregarButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioTextKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE || c == java.awt.event.KeyEvent.VK_DELETE)) {
            evt.consume(); // Ignora la tecla
        }
    }//GEN-LAST:event_anioTextKeyTyped

    private void cargaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cargaTextKeyTyped
        char c = evt.getKeyChar();
        // Solo permite números y el punto
        if (!(Character.isDigit(c) || c == '.' || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        // Evita que pongan más de un punto
        if (c == '.' && ((JTextField)evt.getSource()).getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_cargaTextKeyTyped

    private void kmLitroTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmLitroTextKeyTyped
        char c = evt.getKeyChar();
        // Solo permite números y el punto
        if (!(Character.isDigit(c) || c == '.' || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        // Evita que pongan más de un punto
        if (c == '.' && ((JTextField)evt.getSource()).getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_kmLitroTextKeyTyped

    private void litrosExtraTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_litrosExtraTextKeyTyped
        char c = evt.getKeyChar();
        // Solo permite números y el punto
        if (!(Character.isDigit(c) || c == '.' || c == java.awt.event.KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        // Evita que pongan más de un punto
        if (c == '.' && ((JTextField)evt.getSource()).getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_litrosExtraTextKeyTyped

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        agregarVehiculoView();
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed
   
    /**
     * 
     * @param args the command line arguments
     */
    public void agregarVehiculoView(){
        String nombre = this.marcaText.getText();
        String pais = this.paisText.getText();
        String patente = this.patenteText.getText();
        String modelo = this.modeloText.getText();
        int anio =  Integer.parseInt(this.anioText.getText());
        double capacidad = Double.parseDouble(this.cargaText.getText());
        double kmLitro = Double.parseDouble(this.kmLitroText.getText());
        double litrosExtra = Double.parseDouble(this.litrosExtraText.getText());
        
        boolean result = controlador.altaVehiculo(nombre, pais, patente, modelo, anio, capacidad, kmLitro, litrosExtra);
        
        if(result == true){
            JOptionPane.showMessageDialog(this, "¡Vehiculo ingresado con éxito!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.padre.listarVehiculos();
            this.salirButton.doClick();
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al crear el vehiculo, verifique los campos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaVehiculo().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioText;
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextField anioText;
    private javax.swing.JTextField cargaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField kmLitroText;
    private javax.swing.JTextField litrosExtraText;
    private javax.swing.JTextField marcaText;
    private javax.swing.JTextField modeloText;
    private javax.swing.JTextField paisText;
    private javax.swing.JTextField patenteText;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
